"""add column joined_at

Revision ID: 848a71e2a9de
Revises: 
Create Date: 2023-04-18 16:44:17.394652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '848a71e2a9de'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_table', sa.Column('joined_at', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_table', 'joined_at')
    # ### end Alembic commands ###
